### ISSUE TITLE
Conflict with the Edit Author Slug plugin

### ISSUE THREAD

**Issue by stevejburge** [publishpress/PublishPress-Authors#181]
Based on this documentation https://publishpress.com/knowledge-base/how-to-change-author-urls/

Report: https://wordpress.org/support/topic/conflict-with-edit-author-slug/ 

After changing author URL, you get this error when visting the authors' page:

`Fatal error: Uncaught Error: Object of class WP_Error could not be converted to string in /Users/ynahpantig/code/site/wp/wp-includes/formatting.php:4203 Stack trace: #0 /Users/ynahpantig/code/site/wp/wp-includes/formatting.php(4203): str_replace(Array, Array, Object(WP_Error)) #1 /Users/ynahpantig/code/site/wp/wp-includes/class-wp-hook.php(287): ent2ncr(Object(WP_Error)) #2 /Users/ynahpantig/code/site/wp/wp-includes/plugin.php(206): WP_Hook->apply_filters(Object(WP_Error), Array) #3 /Users/ynahpantig/code/site/content/plugins/publishpress-authors/src/functions/template-tags.php(74): apply_filters('the_author', Object(WP_Error)) #4 /Users/ynahpantig/code/site/content/plugins/publishpress-authors/src/functions/template-tags.php(849): get_multiple_authors(0, true, true) #5 /Users/ynahpantig/code/site/wp/wp-includes/class-wp-hook.php(287): {closure}(Arra in /Users/ynahpantig/code/site/wp/wp-includes/formatting.php on line 4203`

![Screen Shot 2020-08-13 at 1 57 18 PM](https://user-images.githubusercontent.com/3868028/90169676-ef58c480-dd6c-11ea-96f3-6d235200df0c.png)

**Comment by stevejburge** [comment]
From @agapetry 

> the fatal error is simply accessing a $term property after get_term() returns false in template-tags.php
> 
> It looks like that plugin is preventing the author term from being created at new user creation.  At least it does not exist after adding one post and then accessing the author archive. 
>

**Comment by stevejburge** [comment]
More @agapetry 

> After looking at that Authors issue more today (with the old version), I realized the fatal error actually occurs in a default installation without any other plugins.  It happens whenever an author archive url is accessed for a user who does not have an author linked.  There does not seem to be any way to automate that linking with free, so it always happens until the Author link is manually created.
